jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -P\!build-android -nsu -B -Pjacoco install
name: Test Java 8
on:
  repository_dispatch:
    types: trigger-ga___test_java_8.yml
